# Generated by Django 3.0.2 on 2020-05-17 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('numero_campo', models.IntegerField()),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('sets_favor', models.IntegerField(default=0)),
                ('sets_contra', models.IntegerField(default=0)),
                ('juegos_favor', models.IntegerField(default=0)),
                ('juegos_contra', models.IntegerField(default=0)),
                ('puntos_favor', models.IntegerField(default=0)),
                ('puntos_contra', models.IntegerField(default=0)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-partidos_ganados', '-sets_favor', '-puntos_favor', 'puntos_contra'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('numero_equipos', models.IntegerField(null=True)),
                ('numero_grupos', models.IntegerField(default=0)),
                ('numero_sets', models.IntegerField(null=True)),
                ('numero_puntos', models.IntegerField(null=True)),
                ('puntos_maximos', models.IntegerField(null=True)),
                ('tipo_fase', models.IntegerField()),
                ('doble_partid', models.BooleanField()),
                ('esta_terminada', models.BooleanField(default=False)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('campos', models.ManyToManyField(to='cubogt.Campo')),
                ('equipos', models.ManyToManyField(to='cubogt.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('numero_grupo', models.IntegerField()),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(through='cubogt.Clasificacion', to='cubogt.Equipo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Fase')),
            ],
            options={
                'ordering': ['numero_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_favor', models.IntegerField(default=0)),
                ('sets_contra', models.IntegerField(default=0)),
                ('juegos_favor', models.IntegerField(default=0)),
                ('juegos_contra', models.IntegerField(default=0)),
                ('puntos_favor', models.IntegerField(default=0)),
                ('puntos_contra', models.IntegerField(default=0)),
                ('jornada', models.IntegerField()),
                ('esta_terminado', models.BooleanField(default=False)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Campo')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_equipo', to='cubogt.Equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_equipo', to='cubogt.Equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(choices=[('1', 'Fútbol'), ('2', 'Baloncesto'), ('3', 'Voleibol'), ('4', 'Balonmano'), ('5', 'Waterpolo'), ('6', 'Tenis')], default='3', max_length=2)),
                ('estado', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('numero_equipos', models.IntegerField(null=True)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(to='cubogt.Equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.IntegerField()),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visitante', models.IntegerField(default=0)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Partido')),
            ],
            options={
                'ordering': ['numero_set'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Torneo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='integrantes',
            field=models.ManyToManyField(through='cubogt.Jugador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Equipo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Grupo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Torneo'),
        ),
        migrations.CreateModel(
            name='Ascenso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipos', models.IntegerField()),
                ('desde_posicion', models.IntegerField()),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Grupo')),
                ('proxima_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Fase')),
            ],
        ),
    ]
