# Generated by Django 3.0.2 on 2020-06-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deporte',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='deporte',
            old_name='deporte',
            new_name='nombre',
        ),
    ]
