# Generated by Django 3.0.2 on 2020-05-31 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arbitro', to='cubogt.Equipo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='deporte',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol'), ('balonmano', 'Balonmano'), ('waterpolo', 'Waterpolo'), ('tenis', 'Tenis')], default='voleibol', max_length=15),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Creación'), (1, 'Activo'), (2, 'Terminado')], default=0),
        ),
    ]
