# Generated by Django 3.0.2 on 2020-06-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0002_auto_20200602_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='punto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='numero_equipos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
