# Generated by Django 3.0.2 on 2020-06-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0002_auto_20200601_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['fecha']},
        ),
        migrations.RemoveField(
            model_name='campo',
            name='numero_campo',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='fase_numero',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='numero_grupo',
        ),
        migrations.AlterField(
            model_name='campo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
