# Generated by Django 3.0.2 on 2020-06-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0003_auto_20200602_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase',
            old_name='doble_partid',
            new_name='doble_partido',
        ),
        migrations.AddField(
            model_name='set',
            name='juegos_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='juegos_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(default='fase sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fase',
            name='numero_equipos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase',
            name='puntos_maximos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase',
            name='tipo_fase',
            field=models.IntegerField(choices=[(1, 'Liga'), (2, 'Eliminatoria')]),
        ),
        migrations.AlterField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbitro', to='cubogt.Equipo'),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_juego', models.IntegerField()),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visitante', models.IntegerField(default=0)),
                ('UPD', models.DateTimeField(auto_now=True)),
                ('NWD', models.DateTimeField(auto_now_add=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubogt.Set')),
            ],
            options={
                'ordering': ['numero_juego'],
            },
        ),
    ]
