# Generated by Django 3.0.2 on 2020-06-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0004_auto_20200603_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fase',
            old_name='numero_equipos',
            new_name='numero_equipos_max',
        ),
        migrations.RenameField(
            model_name='torneo',
            old_name='numero_equipos',
            new_name='numero_equipos_max',
        ),
    ]
