# Generated by Django 3.0.2 on 2020-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0005_auto_20200608_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ascenso',
            options={'ordering': ['grupo']},
        ),
        migrations.RemoveField(
            model_name='fase',
            name='esta_terminada',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='esta_terminado',
        ),
        migrations.AddField(
            model_name='campo',
            name='libre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Creación'), (1, 'Activo'), (2, 'Terminado')], default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En espera'), (1, 'Jugándose'), (2, 'Terminado')], default=0),
        ),
    ]
