# Generated by Django 3.0.2 on 2020-06-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0006_auto_20200610_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['jornada', 'grupo']},
        ),
        migrations.AlterField(
            model_name='partido',
            name='campo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cubogt.Campo'),
        ),
    ]
