# Generated by Django 3.0.2 on 2020-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0009_auto_20200614_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='juego_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='juego_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
