# Generated by Django 3.0.2 on 2020-06-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0011_auto_20200615_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='puntos_local',
            new_name='resultado_local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='puntos_visitante',
            new_name='resultado_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='juegos_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='juegos_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='sets_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='sets_visitante',
        ),
        migrations.AddField(
            model_name='juego',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cubogt.Equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='cubogt.Equipo'),
        ),
        migrations.AddField(
            model_name='set',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cubogt.Equipo'),
        ),
    ]
