# Generated by Django 3.0.2 on 2020-06-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0012_auto_20200616_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'ordering': ['-partidos_ganados', '-partidos_empatados', '-sets_favor', '-sets_contra', '-juegos_favor', '-juegos_contra', '-puntos_favor', 'puntos_contra']},
        ),
        migrations.AddField(
            model_name='ascenso',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Bien'), (1, 'Tiene error'), (2, 'Ascendido')], default=0),
        ),
    ]
