# Generated by Django 3.0.2 on 2020-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubogt', '0013_auto_20200617_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='prefijo_eliminatoria',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='ascenso',
            name='estado',
            field=models.IntegerField(choices=[(0, 'espera'), (1, 'Tiene error'), (2, 'Realizado')], default=0),
        ),
    ]
